---
layout: home
title: Will Patrone
subtitle: Graduate Student | University of Washington
---

Growing up in South Florida, the aquatic environment was all around me. I frequently spent my days at the beach, snorkeling in the water or collecting shells on the beach. Having ready access to the ocean sparked a love and appreciation for the aquatic environment. 

### Welcome to College!
In the fall of 2019, I began at the University of Florida's Honors Program, where I graduated summa cum laude with a B.S. in Marine Sciences and a B.S. in Environmental Science. I also completed minors in Economics and Zoology, as well as the CALS Honors Scholar certificate. My time in Gainesville was memorable and gave me a strong foundation to grow into the scientist and person I am today. As a freshman, I joined the [Executive Board of Science Olympiad at the University of Florida](https://uf.floridascienceolympiad.org/), a 501(c)(3) nonprofit dedicated to providing K-12 STEM Education through team-based competitions. I initially joined as an event coordinator and webmaster before being promoted to President in March 2020, a role I served in for two and a half years.  I continue to serve as an emeritus member and assist with logistics for tournaments at UF and other universities around the country. I worked with Dr. Randy Penn through the [Active Learning Program](https://caires.center.ufl.edu/education/) and the Green Sports Program to produce marketing materials for Condron Ballpark, the new home of the Gators baseball team. This material highlighted sustainability efforts made in the park's construction, and a video was created for use during home baseball games to highlight these efforts. My honors thesis was advised by Dr. Nick Funicelli, where we examined trends in lionfish abundance in the Florida Keys using citizen science data collected by [REEF](https://www.reef.org/). I also worked in the [Siders Lab](https://www.zachsiders.com/), examining time-at-depth weighted biodiversity trends for shark species of the North Pacific. This research was published in the journal *Ecography*. You can read more about these projects on the [Research](willpatrone.github.io/research) page. 

### In the workforce
After graduating in May 2022, I made the cross-country move to Seattle, Washington, where I accepted a job as a research coordinator with UW's Department of Chemistry. I worked with 45 faculty members on grant acquisitions and renewals, providing support on budgets, sponsor-specific requirements, and university bureaucracy. In January 2023, I transitioned to the Department of Urology and Fred Hutchinson Cancer Research Center to work as a research coordinator with [Canary PASS](https://canarypass.org/) PASS is an active surveillance study of prostate cancer for men across the US and Canada. I worked on specimen management, data acquisition, cleaning, and organization, and served as a pseudo-project manager for specimen data use. 

### Graduate School Grind
In September 2023, I joined the [PuntLab](https://puntlab.washington.edu/) as a master's student under Dr. Andre Punt. My thesis explores multispecies fisheries management of the US West Coast Groundfish fishery, defining métiers to calculate multispecies target reference points. Outside of my thesis work, I am working with Dr. Ray Hilborn on a global analysis of trends in marine biodiversity. You can read more about my current work on the [Research](willpatrone.github.io/research) page.
